### ISSUE TITLE
Request: sendtime command 

### ISSUE THREAD

**Issue by CoolCanuck** [rickz0rz/prevuecommander#5]
Could a command be made to send the new current time? (just the new time, not all programs and other commands)

After a few minutes after sending, my time jumps ahead an hour :(

**Comment by rickz0rz** [comment]
This actually is possible already if you just make a simple playbook with the following:

```
configuration:
  hostname: 127.0.0.1
  port: 1234
  verboseDataOutput: 
commands:
- !!address
  target: '*'
- !!clock
  useCurrentDate: true
  date: 
- !!boxOff {}
```
